{
    "data": {
      "contents": [
        {
          "id": 79684976,
          "type": "TextNote",
          "status": "published",
          "name": "Daily UI #009",
          "description": null,
          "likeCount": 0,
          "price": 0,
          "key": "ne2f6b992a3c9",
          "slug": "slug-ne2f6b992a3c9",
          "publishAt": "2024-03-14T23:06:11+09:00",
          "thumbnailExternalUrl": "",
          "eyecatch": "https://assets.st-note.com/production/uploads/images/134563883/rectangle_large_type_2_ff4ee7eba1053ac8cba22c0878624293.png?fit=bounds&quality=85&width=1280",
          "user": {
            "id": 7514809,
            "key": "f260827237e11f866ef14473358524a8",
            "name": "mayu",
            "urlname": "zhenyou620",
            "nickname": "mayu",
            "userProfileImagePath": "https://assets.st-note.com/production/uploads/images/133940969/profile_d48e9590145bddd89391f59fdb6cd7a9.png?fit=bounds&format=jpeg&quality=85&width=330",
            "customDomain": null,
            "disableSupport": false,
            "disableGuestPurchase": false,
            "emailConfirmedFlag": true,
            "likeAppealText": "ありがとう！励みになります！",
            "likeAppealImage": null,
            "purchaseAppealTextNote": null,
            "twitterNickname": null,
            "shareAppeal": {
              "text": null,
              "image": null
            },
            "magazineAddAppeal": {
              "text": null,
              "image": null
            }
          },
          "canRead": true,
          "isAuthor": true,
          "externalUrl": null,
          "customDomain": null,
          "body": "PromptMusic Player\n\n参考にしたサービスAmazon MusicLINE MUSICYoutube Musicミュージック(Apple)Spotify思ったこと必須要素は以下\n\nタイトル\n\nアーティスト名\n\nジャケット\n\nコントロール\n\n検索画面や曲一覧画面に戻るためのボタン\n\nお気に入りボタン\n\n以下のもので代替できる\n\nお気に入り\n\nリストに追加\n\n高評価\n\n必ずしも必須ではない\n\n共有ボタン\n\nプレイリストの曲一覧ボタン\n\n歌詞\n\n背景色はジャケットの",
          "separator": null,
          "isLimited": false,
          "isTrial": false,
          "canUpdate": true,
          "tweetText": "Daily UI #009｜mayu #note",
          "twitterRelatedAccounts": "note_PR",
          "isRefund": false,
          "isLiked": false,
          "commentCount": 0,
          "likes": [],
          "anonymousLikeCount": 0,
          "disableComment": false,
          "hashtags": [],
          "twitterShareUrl": "https://twitter.com/intent/tweet?url=https://note.com/zhenyou620/n/ne2f6b992a3c9&text=Daily+UI+%23009%EF%BD%9Cmayu+%23note&related=note_PR",
          "facebookShareUrl": "https://www.facebook.com/share.php?u=https://note.com/zhenyou620/n/ne2f6b992a3c9&t=Daily+UI+%23009%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89",
          "lineShareUrl": "https://line.naver.jp/R/msg/text/?Daily+UI+%23009%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89%0Ahttps://note.com/zhenyou620/n/ne2f6b992a3c9",
          "audio": {
  
          },
          "pictures": [],
          "limitedMessage": null,
          "labels": [],
          "priorSale": null,
          "canMultipleLimitedNote": true,
          "isMembershipConnected": false,
          "hasAvailableCirclePlans": false,
          "isPinned": false,
          "pinnedUserNoteId": null,
          "spEyecatch": "https://assets.st-note.com/production/uploads/images/134563883/square_large_ff4ee7eba1053ac8cba22c0878624293.png?fit=bounds&format=jpeg&quality=85&width=360",
          "enableBacktoDraft": true,
          "notificationMessages": [],
          "isProfiled": false,
          "isForWork": false,
          "isCircleDescription": false,
          "noteDraft": null,
          "noteUrl": "https://note.com/zhenyou620/n/ne2f6b992a3c9",
          "imageCount": 7,
          "format": "4.0",
          "capabilities": {
            "rubyText": true,
            "formulaText": true,
            "duplication": true
          },
          "discountCampaigns": [],
          "freeBodyCharNum": 216
        },
        {
          "id": 79637144,
          "type": "TextNote",
          "status": "published",
          "name": "Daily UI #008",
          "description": null,
          "likeCount": 1,
          "price": 0,
          "key": "n0beb6dcc93b0",
          "slug": "slug-n0beb6dcc93b0",
          "publishAt": "2024-03-14T23:03:32+09:00",
          "thumbnailExternalUrl": "",
          "eyecatch": "https://assets.st-note.com/production/uploads/images/134563552/rectangle_large_type_2_eb8d610e6bd0ba7adddb88d71d93b40c.png?fit=bounds&quality=85&width=1280",
          "user": {
            "id": 7514809,
            "key": "f260827237e11f866ef14473358524a8",
            "name": "mayu",
            "urlname": "zhenyou620",
            "nickname": "mayu",
            "userProfileImagePath": "https://assets.st-note.com/production/uploads/images/133940969/profile_d48e9590145bddd89391f59fdb6cd7a9.png?fit=bounds&format=jpeg&quality=85&width=330",
            "customDomain": null,
            "disableSupport": false,
            "disableGuestPurchase": false,
            "emailConfirmedFlag": true,
            "likeAppealText": "ありがとう！励みになります！",
            "likeAppealImage": null,
            "purchaseAppealTextNote": null,
            "twitterNickname": null,
            "shareAppeal": {
              "text": null,
              "image": null
            },
            "magazineAddAppeal": {
              "text": null,
              "image": null
            }
          },
          "canRead": true,
          "isAuthor": true,
          "externalUrl": null,
          "customDomain": null,
          "body": "Prompt404 Page Design\n\n参考にしたデザインNotionDribbbleGitHubFigmaBehanceChatGPTnote思ったこと硬い感じのもあれば遊び心があるものもある\n\n何かの本で、エラーページは遊び心を持たせることでユーザのイラつきを無くしてブランド力を高めることができるみたいなのを読んだ気がする\n\nベクターをいじれたり色を変えられたりするのはかなり遊び心あって面白いところ\n\nnote美術館とか発想がすごい\n\nGoogleとかはゲームできた",
          "separator": null,
          "isLimited": false,
          "isTrial": false,
          "canUpdate": true,
          "tweetText": "Daily UI #008｜mayu #note",
          "twitterRelatedAccounts": "note_PR",
          "isRefund": false,
          "isLiked": false,
          "commentCount": 0,
          "likes": [],
          "anonymousLikeCount": 0,
          "disableComment": false,
          "hashtags": [],
          "twitterShareUrl": "https://twitter.com/intent/tweet?url=https://note.com/zhenyou620/n/n0beb6dcc93b0&text=Daily+UI+%23008%EF%BD%9Cmayu+%23note&related=note_PR",
          "facebookShareUrl": "https://www.facebook.com/share.php?u=https://note.com/zhenyou620/n/n0beb6dcc93b0&t=Daily+UI+%23008%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89",
          "lineShareUrl": "https://line.naver.jp/R/msg/text/?Daily+UI+%23008%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89%0Ahttps://note.com/zhenyou620/n/n0beb6dcc93b0",
          "audio": {
  
          },
          "pictures": [],
          "limitedMessage": null,
          "labels": [],
          "priorSale": null,
          "canMultipleLimitedNote": true,
          "isMembershipConnected": false,
          "hasAvailableCirclePlans": false,
          "isPinned": false,
          "pinnedUserNoteId": null,
          "spEyecatch": "https://assets.st-note.com/production/uploads/images/134563552/square_large_eb8d610e6bd0ba7adddb88d71d93b40c.png?fit=bounds&format=jpeg&quality=85&width=360",
          "enableBacktoDraft": true,
          "notificationMessages": [],
          "isProfiled": false,
          "isForWork": false,
          "isCircleDescription": false,
          "noteDraft": null,
          "noteUrl": "https://note.com/zhenyou620/n/n0beb6dcc93b0",
          "imageCount": 9,
          "format": "4.0",
          "capabilities": {
            "rubyText": true,
            "formulaText": true,
            "duplication": true
          },
          "discountCampaigns": [],
          "freeBodyCharNum": 274
        },
        {
          "id": 79499431,
          "type": "TextNote",
          "status": "published",
          "name": "Daily UI #007",
          "description": null,
          "likeCount": 0,
          "price": 0,
          "key": "n804db196fc59",
          "slug": "slug-n804db196fc59",
          "publishAt": "2024-01-27T18:47:17+09:00",
          "thumbnailExternalUrl": "",
          "eyecatch": "https://assets.st-note.com/production/uploads/images/134563200/rectangle_large_type_2_4d6354acecb607a6ea9676cfdbf5b6a1.png?fit=bounds&quality=85&width=1280",
          "user": {
            "id": 7514809,
            "key": "f260827237e11f866ef14473358524a8",
            "name": "mayu",
            "urlname": "zhenyou620",
            "nickname": "mayu",
            "userProfileImagePath": "https://assets.st-note.com/production/uploads/images/133940969/profile_d48e9590145bddd89391f59fdb6cd7a9.png?fit=bounds&format=jpeg&quality=85&width=330",
            "customDomain": null,
            "disableSupport": false,
            "disableGuestPurchase": false,
            "emailConfirmedFlag": true,
            "likeAppealText": "ありがとう！励みになります！",
            "likeAppealImage": null,
            "purchaseAppealTextNote": null,
            "twitterNickname": null,
            "shareAppeal": {
              "text": null,
              "image": null
            },
            "magazineAddAppeal": {
              "text": null,
              "image": null
            }
          },
          "canRead": true,
          "isAuthor": true,
          "externalUrl": null,
          "customDomain": null,
          "body": "Promptsetting\n006で作ったSNSの設定画面を作ることにする\n\n参考にしたサービスThreadsBehanceGitHubInstagram思ったことでかいSNSになるほど、設定項目が増えていく。インスタは見切れているが、この下に大量の項目があった。規模感やサービスの考えによって設定項目は大幅に変わりそう。\n\nThreadsくらいの量が一番みやすい\n\nよくあるのは以下の項目？\n\n通知設定\n\nアカウント設定\n\nヘルプ\n\nログアウト\n\nフィードバック\n\nプライバシー",
          "separator": null,
          "isLimited": false,
          "isTrial": false,
          "canUpdate": true,
          "tweetText": "Daily UI #007｜mayu #note",
          "twitterRelatedAccounts": "note_PR",
          "isRefund": false,
          "isLiked": false,
          "commentCount": 0,
          "likes": [],
          "anonymousLikeCount": 0,
          "disableComment": false,
          "hashtags": [
            {
              "hashtag": {
                "name": "#006で作ったSNSの設定画面を作ることにする"
              }
            }
          ],
          "twitterShareUrl": "https://twitter.com/intent/tweet?url=https://note.com/zhenyou620/n/n804db196fc59&text=Daily+UI+%23007%EF%BD%9Cmayu+%23note&related=note_PR",
          "facebookShareUrl": "https://www.facebook.com/share.php?u=https://note.com/zhenyou620/n/n804db196fc59&t=Daily+UI+%23007%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89",
          "lineShareUrl": "https://line.naver.jp/R/msg/text/?Daily+UI+%23007%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89%0Ahttps://note.com/zhenyou620/n/n804db196fc59",
          "audio": {
  
          },
          "pictures": [],
          "limitedMessage": null,
          "labels": [],
          "priorSale": null,
          "canMultipleLimitedNote": true,
          "isMembershipConnected": false,
          "hasAvailableCirclePlans": false,
          "isPinned": false,
          "pinnedUserNoteId": null,
          "spEyecatch": "https://assets.st-note.com/production/uploads/images/134563200/square_large_4d6354acecb607a6ea9676cfdbf5b6a1.png?fit=bounds&format=jpeg&quality=85&width=360",
          "enableBacktoDraft": true,
          "notificationMessages": [],
          "isProfiled": false,
          "isForWork": false,
          "isCircleDescription": false,
          "noteDraft": null,
          "noteUrl": "https://note.com/zhenyou620/n/n804db196fc59",
          "imageCount": 6,
          "format": "4.0",
          "capabilities": {
            "rubyText": true,
            "formulaText": true,
            "duplication": true
          },
          "discountCampaigns": [],
          "freeBodyCharNum": 349
        },
        {
          "id": 78897296,
          "type": "TextNote",
          "status": "published",
          "name": "Daily UI #006",
          "description": null,
          "likeCount": 1,
          "price": 0,
          "key": "nf3425e414c07",
          "slug": "slug-nf3425e414c07",
          "publishAt": "2024-01-25T08:07:15+09:00",
          "thumbnailExternalUrl": "",
          "eyecatch": "https://assets.st-note.com/production/uploads/images/134562946/rectangle_large_type_2_0447d8c3123f72d2d7868c8983fe5e7b.png?fit=bounds&quality=85&width=1280",
          "user": {
            "id": 7514809,
            "key": "f260827237e11f866ef14473358524a8",
            "name": "mayu",
            "urlname": "zhenyou620",
            "nickname": "mayu",
            "userProfileImagePath": "https://assets.st-note.com/production/uploads/images/133940969/profile_d48e9590145bddd89391f59fdb6cd7a9.png?fit=bounds&format=jpeg&quality=85&width=330",
            "customDomain": null,
            "disableSupport": false,
            "disableGuestPurchase": false,
            "emailConfirmedFlag": true,
            "likeAppealText": "ありがとう！励みになります！",
            "likeAppealImage": null,
            "purchaseAppealTextNote": null,
            "twitterNickname": null,
            "shareAppeal": {
              "text": null,
              "image": null
            },
            "magazineAddAppeal": {
              "text": null,
              "image": null
            }
          },
          "canRead": true,
          "isAuthor": true,
          "externalUrl": null,
          "customDomain": null,
          "body": "PromptUser Profile\n\n参考にしたサービスDribbbleZennしずかなインターネットフローティングボタンですぐ自分のホームに戻れるのが珍しい感じする。\nフォローではなく「購読」ができる？\n\nThreadsBehanceGithubMastodonInstagram思ったことアイコン画像は必須。プロフィールが必要なサービスはほぼSNSだからそれはそうだろう。\n\n背景画像はないサービスもある。てか多そう。\n\nそのサービスで、個人を識別する上で大事なものが一番大",
          "separator": null,
          "isLimited": false,
          "isTrial": false,
          "canUpdate": true,
          "tweetText": "Daily UI #006｜mayu #note",
          "twitterRelatedAccounts": "note_PR",
          "isRefund": false,
          "isLiked": false,
          "commentCount": 0,
          "likes": [],
          "anonymousLikeCount": 0,
          "disableComment": false,
          "hashtags": [],
          "twitterShareUrl": "https://twitter.com/intent/tweet?url=https://note.com/zhenyou620/n/nf3425e414c07&text=Daily+UI+%23006%EF%BD%9Cmayu+%23note&related=note_PR",
          "facebookShareUrl": "https://www.facebook.com/share.php?u=https://note.com/zhenyou620/n/nf3425e414c07&t=Daily+UI+%23006%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89",
          "lineShareUrl": "https://line.naver.jp/R/msg/text/?Daily+UI+%23006%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89%0Ahttps://note.com/zhenyou620/n/nf3425e414c07",
          "audio": {
  
          },
          "pictures": [],
          "limitedMessage": null,
          "labels": [],
          "priorSale": null,
          "canMultipleLimitedNote": true,
          "isMembershipConnected": false,
          "hasAvailableCirclePlans": false,
          "isPinned": false,
          "pinnedUserNoteId": null,
          "spEyecatch": "https://assets.st-note.com/production/uploads/images/134562946/square_large_0447d8c3123f72d2d7868c8983fe5e7b.png?fit=bounds&format=jpeg&quality=85&width=360",
          "enableBacktoDraft": true,
          "notificationMessages": [],
          "isProfiled": false,
          "isForWork": false,
          "isCircleDescription": false,
          "noteDraft": null,
          "noteUrl": "https://note.com/zhenyou620/n/nf3425e414c07",
          "imageCount": 10,
          "format": "4.0",
          "capabilities": {
            "rubyText": true,
            "formulaText": true,
            "duplication": true
          },
          "discountCampaigns": [],
          "freeBodyCharNum": 465
        },
        {
          "id": 78609856,
          "type": "TextNote",
          "status": "published",
          "name": "Daily UI #005",
          "description": null,
          "likeCount": 0,
          "price": 0,
          "key": "na14e84f85f35",
          "slug": "slug-na14e84f85f35",
          "publishAt": "2024-01-14T18:50:02+09:00",
          "thumbnailExternalUrl": "",
          "eyecatch": "https://assets.st-note.com/production/uploads/images/134562427/rectangle_large_type_2_1f79b1ed0512da4762d88fca31e8ec11.png?fit=bounds&quality=85&width=1280",
          "user": {
            "id": 7514809,
            "key": "f260827237e11f866ef14473358524a8",
            "name": "mayu",
            "urlname": "zhenyou620",
            "nickname": "mayu",
            "userProfileImagePath": "https://assets.st-note.com/production/uploads/images/133940969/profile_d48e9590145bddd89391f59fdb6cd7a9.png?fit=bounds&format=jpeg&quality=85&width=330",
            "customDomain": null,
            "disableSupport": false,
            "disableGuestPurchase": false,
            "emailConfirmedFlag": true,
            "likeAppealText": "ありがとう！励みになります！",
            "likeAppealImage": null,
            "purchaseAppealTextNote": null,
            "twitterNickname": null,
            "shareAppeal": {
              "text": null,
              "image": null
            },
            "magazineAddAppeal": {
              "text": null,
              "image": null
            }
          },
          "canRead": true,
          "isAuthor": true,
          "externalUrl": null,
          "customDomain": null,
          "body": "PromptApp Icon\n\n参考にしたサービスApplemacOS\n\nとりあえずDockのアイコンをみてみる\n\niOS\n\nGoogleiOS\n\nこんなにサービスあったんか\n\nその他今まで参考にしてきたサービスのアイコン。サービス自体のロゴ。\n大体白か黒の背景？\n\nHuman Interface Guidelineshttps://developer.apple.com/design/human-interface-guidelines/app-icons\n\nシンプルさを重",
          "separator": null,
          "isLimited": false,
          "isTrial": false,
          "canUpdate": true,
          "tweetText": "Daily UI #005｜mayu #note",
          "twitterRelatedAccounts": "note_PR",
          "isRefund": false,
          "isLiked": false,
          "commentCount": 0,
          "likes": [],
          "anonymousLikeCount": 0,
          "disableComment": false,
          "hashtags": [
            {
              "hashtag": {
                "name": "#003で作ったLPのサービスのアイコンをアレンジ"
              }
            }
          ],
          "twitterShareUrl": "https://twitter.com/intent/tweet?url=https://note.com/zhenyou620/n/na14e84f85f35&text=Daily+UI+%23005%EF%BD%9Cmayu+%23note&related=note_PR",
          "facebookShareUrl": "https://www.facebook.com/share.php?u=https://note.com/zhenyou620/n/na14e84f85f35&t=Daily+UI+%23005%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89",
          "lineShareUrl": "https://line.naver.jp/R/msg/text/?Daily+UI+%23005%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89%0Ahttps://note.com/zhenyou620/n/na14e84f85f35",
          "audio": {
  
          },
          "pictures": [],
          "limitedMessage": null,
          "labels": [],
          "priorSale": null,
          "canMultipleLimitedNote": true,
          "isMembershipConnected": false,
          "hasAvailableCirclePlans": false,
          "isPinned": false,
          "pinnedUserNoteId": null,
          "spEyecatch": "https://assets.st-note.com/production/uploads/images/134562427/square_large_1f79b1ed0512da4762d88fca31e8ec11.png?fit=bounds&format=jpeg&quality=85&width=360",
          "enableBacktoDraft": true,
          "notificationMessages": [],
          "isProfiled": false,
          "isForWork": false,
          "isCircleDescription": false,
          "noteDraft": null,
          "noteUrl": "https://note.com/zhenyou620/n/na14e84f85f35",
          "imageCount": 14,
          "format": "4.0",
          "capabilities": {
            "rubyText": true,
            "formulaText": true,
            "duplication": true
          },
          "discountCampaigns": [],
          "freeBodyCharNum": 476
        },
        {
          "id": 78505039,
          "type": "TextNote",
          "status": "published",
          "name": "Daily UI #004",
          "description": null,
          "likeCount": 1,
          "price": 0,
          "key": "neb9c8fd3b26b",
          "slug": "slug-neb9c8fd3b26b",
          "publishAt": "2024-01-09T07:35:11+09:00",
          "thumbnailExternalUrl": "",
          "eyecatch": "https://assets.st-note.com/production/uploads/images/134562121/rectangle_large_type_2_d5737df389032d486f4fb4967d46d4d2.png?fit=bounds&quality=85&width=1280",
          "user": {
            "id": 7514809,
            "key": "f260827237e11f866ef14473358524a8",
            "name": "mayu",
            "urlname": "zhenyou620",
            "nickname": "mayu",
            "userProfileImagePath": "https://assets.st-note.com/production/uploads/images/133940969/profile_d48e9590145bddd89391f59fdb6cd7a9.png?fit=bounds&format=jpeg&quality=85&width=330",
            "customDomain": null,
            "disableSupport": false,
            "disableGuestPurchase": false,
            "emailConfirmedFlag": true,
            "likeAppealText": "ありがとう！励みになります！",
            "likeAppealImage": null,
            "purchaseAppealTextNote": null,
            "twitterNickname": null,
            "shareAppeal": {
              "text": null,
              "image": null
            },
            "magazineAddAppeal": {
              "text": null,
              "image": null
            }
          },
          "canRead": true,
          "isAuthor": true,
          "externalUrl": null,
          "customDomain": null,
          "body": "PromptCalculation\n\nCalculatorではなくCalculation？\n\n電卓アプリでなくてもよさそう\n\nメールにはこう書いてあった\n\nちょっと思いつかないので普通にデスクトップ用の電卓アプリ作る\n\n参考にしたサービスApple\n\n背景が半透明になっており、他のアプリと併用しやすい。\n\n角が丸くてかわいい\n\nプログラマだけどこんなの使ったことない\n\n計算履歴は別途出てくる\n\nWindowshttps://apps.microsoft.com/detail/",
          "separator": null,
          "isLimited": false,
          "isTrial": false,
          "canUpdate": true,
          "tweetText": "Daily UI #004｜mayu #note",
          "twitterRelatedAccounts": "note_PR",
          "isRefund": false,
          "isLiked": false,
          "commentCount": 0,
          "likes": [],
          "anonymousLikeCount": 0,
          "disableComment": false,
          "hashtags": [],
          "twitterShareUrl": "https://twitter.com/intent/tweet?url=https://note.com/zhenyou620/n/neb9c8fd3b26b&text=Daily+UI+%23004%EF%BD%9Cmayu+%23note&related=note_PR",
          "facebookShareUrl": "https://www.facebook.com/share.php?u=https://note.com/zhenyou620/n/neb9c8fd3b26b&t=Daily+UI+%23004%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89",
          "lineShareUrl": "https://line.naver.jp/R/msg/text/?Daily+UI+%23004%EF%BD%9Cmayu%EF%BD%9Cnote%EF%BC%88%E3%83%8E%E3%83%BC%E3%83%88%EF%BC%89%0Ahttps://note.com/zhenyou620/n/neb9c8fd3b26b",
          "audio": {
  
          },
          "pictures": [],
          "limitedMessage": null,
          "labels": [],
          "priorSale": null,
          "canMultipleLimitedNote": true,
          "isMembershipConnected": false,
          "hasAvailableCirclePlans": false,
          "isPinned": false,
          "pinnedUserNoteId": null,
          "spEyecatch": "https://assets.st-note.com/production/uploads/images/134562121/square_large_d5737df389032d486f4fb4967d46d4d2.png?fit=bounds&format=jpeg&quality=85&width=360",
          "enableBacktoDraft": true,
          "notificationMessages": [],
          "isProfiled": false,
          "isForWork": false,
          "isCircleDescription": false,
          "noteDraft": null,
          "noteUrl": "https://note.com/zhenyou620/n/neb9c8fd3b26b",
          "imageCount": 13,
          "format": "4.0",
          "capabilities": {
            "rubyText": true,
            "formulaText": true,
            "duplication": true
          },
          "discountCampaigns": [],
          "freeBodyCharNum": 937
        }
      ],
      "isLastPage": false,
      "totalCount": 9
    }
  }