import type SkillsDetailType from '../types/SkillsDetailType';

const skillsData: SkillsDetailType[] = [
  {
    url: '/src/assets/imgs/js.png',
    altText: 'JavaScript img',
    name: 'JavaScript',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/src/assets/imgs/ts.png',
    altText: 'TypeScript img',
    name: 'Typescript',
    percentage: 20,
    category: 'language',
  },
  {
    url: '/src/assets/imgs/html.svg',
    altText: 'HTML img',
    name: 'HTML',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/src/assets/imgs/css.svg',
    altText: 'CSS img',
    name: 'CSS',
    percentage: 80,
    category: 'language',
  },
  {
    url: 'src/assets/imgs/csharp.svg',
    altText: 'C# img',
    name: 'C#',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/src/assets/imgs/vb.svg',
    altText: 'VB.NET img',
    name: 'VB.NET',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/src/assets/imgs/postgresql.svg',
    altText: 'SQL img',
    name: 'PostgreSQL',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/src/assets/imgs/vue.svg',
    altText: 'Vue.js img',
    name: 'Vue.js',
    percentage: 80,
    category: 'framework',
  },
  {
    url: '/src/assets/imgs/react.svg',
    altText: 'React img',
    name: 'React',
    percentage: 20,
    category: 'framework',
  },
  {
    url: '/src/assets/imgs/jquery.svg',
    altText: 'jQuery img',
    name: 'jQuery',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/src/assets/imgs/nextjs.svg',
    altText: 'Next.js img',
    name: 'Next.js ',
    percentage: 20,
    category: 'framework',
  },
  {
    url: '/src/assets/imgs/figma.svg',
    altText: 'Figma img',
    name: 'Figma',
    percentage: 80,
    category: 'tool',
  },
  {
    url: '/src/assets/imgs/git.svg',
    altText: 'Git img',
    name: 'Git',
    percentage: 80,
    category: 'tool',
  },
  {
    url: '/src/assets/imgs/docker.svg',
    altText: 'Docker img',
    name: 'Docker',
    percentage: 40,
    category: 'tool',
  },
  {
    url: '/src/assets/imgs/aws.svg',
    altText: 'AWS img',
    name: 'AWS',
    percentage: 20,
    category: 'tool',
  },
];
export default skillsData;
